### ISSUE TITLE
VHDL2008: output port in sensitivity list

### ISSUE THREAD

**Issue by pacalet** [tgingold/ghdl#326] opened 2017-03-27 11:02 UTC
VHDL 2008 allows reading an output port but GHDL seems to have a restricted interpretation of this:
```VHDL
-- File foo.vhd
entity foo is
	port(a, b: out bit);
end entity foo;
architecture bug of foo is
begin
	a <= '0', '1' after 1 ns, '0' after 2 ns, '1' after 3 ns;
	process(a)
	begin
		b <= not a;
	end process;
end architecture bug;
```
Results in:
```Bash
$ ghdl -a --std=08 hdl/ghdl_bugs/foo.vhd 
hdl/ghdl_bugs/foo.vhd:7:16:error: 'a' of mode out can't be in a sensivity list
ghdl:error: compilation error
```
While:
```VHDL
-- File bar.vhd
entity bar is
	port(a, b: out bit);
end entity bar;
architecture gub of bar is
begin
	a <= '0', '1' after 1 ns, '0' after 2 ns, '1' after 3 ns;
	process(all)
	begin
		b <= not a;
	end process;
end architecture gub;
```
Results in:
```Bash
$ ghdl -a --std=08 hdl/ghdl_bugs/bar.vhd
$ ghdl -e --std=08 bar
$ ./bar --vcd=-  | gtkwave  --vcd
```

The latter shows the expected behavior. I tried to clear this with the LRM but I have no definite answer about whether output ports shall be allowed in sensitivity lists or not. My intuition is that they should but I did not find a clear statement that confirms my intuition. But whatever the decision on this, isn't it a bit strange that a compilation error is raised on the first code and not on the second?

----------------------
```Bash
$ ghdl -v
GHDL 0.34-dev (2017-03-01-29-g1814966) [Dunoon edition]
 Compiled with GNAT Version: 4.9.2
 llvm code generator
```

**Comment by tgingold** [comment] 2017-03-27 18:30
On 27/03/17 13:02, pacalet wrote:
> I tried to clear this with the LRM but I have no definite answer about
> whether output ports shall be allowed in sensitivity lists or not. But
> whatever the decision on this, isn't it a bit strange that a compilation
> error is raised on the first code and not on the second?

Dear R. Pacalet,

this issue is now fixed.  The check is now relaxed for vhdl 2008.
It works for process(all) because the analyzer automatically extract the 
sensitivity list without checking whether is it readable or not.

**Comment by pacalet** [comment] 2017-03-28 05:58
Thanks. Did you push?

**Comment by tgingold** [comment] 2017-03-28 06:00
On 28/03/17 07:58, pacalet wrote:
> Thanks. Did you push?

Not yet, but as soon as it passes the regression testsuite.

**Closed** 2017-03-28 16:57 UTC
