### ISSUE TITLE
Error with ftabstop and options.c

### ISSUE THREAD

**Issue by rqou** [tgingold/ghdl#325] opened 2017-03-27 08:31 UTC
Compiling GHDL with the GCC backend with GCC version 6.3.0 (using Debian Sid) gives the following error:

```
options.c:1813:2: error: #error Multiple different help strings for ftabstop=:
```

Adding a period at the end of the `-ftabstop=<number>	Distance between tab stops for column reporting` line in `gcc/vhdl/lang.opt` seems to fix it.

**Comment by tgingold** [comment] 2017-03-27 18:43
On 27/03/17 10:31, Robert Ou wrote:
> Compiling GHDL with the GCC backend with GCC version 6.3.0 (using Debian
> Sid) gives the following error:
>
> |options.c:1813:2: error: #error Multiple different help strings for
> ftabstop=: |
>
> Adding a period at the end of the |-ftabstop=<number> Distance between
> tab stops for column reporting| line in |gcc/vhdl/lang.opt| seems to fix it.

I think it would be better to remove the help line in lang.opt
Adding a dot would make it incompatible with previous versions of gcc :-(

**Comment by tgingold** [comment] 2017-03-29 01:37
Should be fixed.  Please, reopen if the issue is still present.

**Closed by tgingold** 2017-03-29 01:37 UTC
Labels: Build: Makefile
