### ISSUE TITLE
Different Overflow Behavior when Using Literals or Variables in Expression

### ISSUE THREAD

**Issue by preusser** [tgingold/ghdl#258] opened 2017-01-17 16:02 UTC
Using `GHDL 0.34-dev (2016-09-14-319-gb42069e0) [Dunoon edition]`, two arithmetically identical expressions are treated differently depending on whether one of the operands is a literal or also a variable. Is this intentional?

Test entity:
```vhdl
entity range_tb is
end range_tb;

architecture tb of range_tb is
begin
  process
    variable i : integer;
  begin

    -- Behaves like 32-bit arithmetic with modular truncation
    i := integer'low;
    report integer'image(i);
    i := integer'low-1;
    report integer'image(i);

    -- Produces the error "overflow detected"
    i := integer'low;
    report integer'image(i);
    i := i-1;
    report integer'image(i);

    wait; -- forever
  end process;
end tb;
```

**Comment by Paebbels** [comment] 2017-01-17 16:08
Possible duplicate of: [Missing bound check failure for user defined integer](https://github.com/tgingold/ghdl/issues/255)

**Comment by tgingold** [comment] 2017-01-18 04:37
Indeed, an error must be reported for line 13.

**Closed** 2017-01-21 12:52 UTC
