### ISSUE TITLE
Analysis Crashes on Taking Second-Level Attributes of Array Subtype

### ISSUE THREAD

**Issue by preusser** [tgingold/ghdl#273] opened 2017-02-09 16:53 UTC
The `'subtype` attribute [LRM §16.2.2, VHDL 2008] gives access to the fully constrained subtype of an object like a variable. This feature works for scalars and arrays. For scalars, it is currently the only way to retrieve information about the exact bounds of the backing subtype - through the use of second-level attributes like `'left`. For arrays, such a two-stage approach is unnecessary but nonetheless legal. While ghdl manages to retrieve an array subtype - as for typing another variable, its analysis chokes when this subtype is queried for a second-level attribute as demonstrated by the testbench below.

```vhdl
entity test is
end test;

architecture tb of test is
begin
  process
    variable a  : integer range 7 downto 0;
    variable b  : a'subtype;
    variable av : bit_vector(7 downto 0);
    variable bv : av'subtype;
  begin
    report integer'image(b'subtype'left);
    report integer'image(bv'left);

    -- The following line crashes the analysis.
    report integer'image(av'subtype'left);

    wait; -- forever
  end process;
end tb;
```

**Comment by Paebbels** [comment] 2017-02-09 17:03
Possible duplicate of [Attribute 'subtype does not work](https://github.com/tgingold/ghdl/issues/253).

**Comment by preusser** [comment] 2017-02-10 07:54
How can a concrete _persisting_ bug be a _duplicate_ of an already resolved issue?

**Comment by tgingold** [comment] 2017-02-24 18:01
I can reproduce the crash.  Investigating.

**Closed** 2017-02-26 14:40 UTC

**Comment by preusser** [comment] 2017-02-28 14:19
Thanks.
