### ISSUE TITLE
ghdl -e error

### ISSUE THREAD

**Issue by rsc9421** [tgingold/ghdl#422] opened 2017-09-28 22:11 UTC
Hi all, I try to compile an example with ghdl in ubuntu 17, but i get some error when i put the command "ghdl -e name_of_entity" , the capture below shows this
![captura de pantalla de 2017-09-28 17-25-57](https://user-images.githubusercontent.com/13366644/30992452-5d36cdfe-a480-11e7-94ae-d1abb0dbd840.png)

any response would very helpful, regards

**Comment by Paebbels** [comment] 2017-09-28 22:22
What GHDL version are you using?
What Ubuntu version are you using: 17.04 or 17.10?

We fixed such a problem for Debian testing some months ago. Maybe we need to adjust the makefiles for Ubuntu 17, too. The problem is that GCC change the behavior of Position Independent Code (PIC). GHDL is generating code differently on your system than the code shipped with some precompiled GHDL parts. The linker complains about different PIC settings of the input files.

----------------------
See also: [Has GCCs -fPIC behavior changed?](https://github.com/tgingold/ghdl/issues/213)

**Comment by rsc9421** [comment] 2017-09-28 22:30
ghdl version 0.33
how to see ghdl backend?
ubuntu 17.04

**Comment by Paebbels** [comment] 2017-09-28 23:30
Use `ghdl --version`.

Version 0.33 is quite old (Sept. 2015).
Can you update to the [`0.34` release](https://github.com/tgingold/ghdl/releases/tag/v0.34) which was release several weeks ago. The mentioned issue was fixed in `0.34`. You can also build GHDL locally to get the latest 0.35 pre-release called `0.35-dev`.

**Comment by rsc9421** [comment] 2017-09-29 04:01
Yes, I compile 0.35-dev and works very fine, thanks!

**Closed** 2017-09-29 05:38 UTC
Labels: Build: Makefile, v0.33
