### ISSUE TITLE
Alias problem

### ISSUE THREAD

**Issue by LarsAsplund** [tgingold/ghdl#293] opened 2017-02-20 10:28 UTC
Running the testbench below results in a failing assert but it works if I remove the alias. Note that the alias isn't used.

``` vhdl
library vunit_lib;
context vunit_lib.vunit_context;

library ieee;
use ieee.float_pkg.all;

entity tb_test is
  generic (
    runner_cfg : string);
end tb_test;

architecture tb of tb_test is
begin
    test_runner : process
      alias fp32 is float32;
    begin
      test_runner_setup(runner, runner_cfg);

      assert zerofp = neg_zerofp;

      test_runner_cleanup(runner);
      wait;
    end process test_runner;
end;
```

**Comment by tgingold** [comment] 2017-02-23 19:49
I can reproduce the issue.  Interesting!

**Comment by LarsAsplund** [comment] 2017-02-23 19:51
Yes, that's a rather weird bug!

**Comment by tgingold** [comment] 2017-02-23 19:56
Thinking twice (and re-reading the vhdl08 LRM), it is not a bug but a feature:
6.6.3 e)
Finally, if the name denotes a type or a subtype, then implicit alias declarations for each predefined operation

So when the alias is present, the implicit "=" operator is visible instead of the overriding one.

Not user friendly feature!

**Comment by tgingold** [comment] 2017-02-23 20:01
I will close this issue, but feel free to comment or argue 😄

**Comment by LarsAsplund** [comment] 2017-02-23 20:02
Please do. I will read and try to understand.

**Comment by LarsAsplund** [comment] 2017-02-23 20:46
Ok, so I will get an implicit alias for "=" that maps to the "=" defined float32. The original failing code looked more like this

``` vhdl
library vunit_lib;
context vunit_lib.vunit_context;

library ieee;
use ieee.float_pkg.all;

entity tb_test2 is
  generic (
    runner_cfg : string);
end tb_test2;

architecture tb of tb_test2 is
begin
    test_runner : process
      alias fp32 is float32;
      constant zero0   : fp32 := zerofp;
      constant negzero : fp32 := neg_zerofp;
    begin
      test_runner_setup(runner, runner_cfg);

      assert zero0 = negzero;

      test_runner_cleanup(runner);
      wait;
    end process test_runner;
end;
```

Isn't the "=" I get the one I want? If I remove the alias and replace `fp32` with `float32` it works.

**Comment by tgingold** [comment] 2017-02-24 02:56
No, you don't get the "=" you need.  You get the predefined "=" that compare bits to bits, instead of the user defined "=" that knowns 0.0 = -0.0

**Closed** 2017-02-24 17:47 UTC

**Comment by LarsAsplund** [comment] 2017-02-24 21:47
Oh, I see. The key is the word _predefined_. That's a horrible feature! It's seems like ModelSim and Aldec's simulators ignored that. They all use the user defined "="
